// Language mapping based on the CSV data from "Languages list for Shunya labs - Updated.csv"
// This file provides a clean interface for the language dropdown
import { mergedLanguages } from "../../../utils/languages";
import { mergedRegions } from "../../../utils/languages";
import { STTMedMergedRegions } from "../../../utils/languages";
export interface LanguageOption {
  name: string; // Display name for frontend
  code: string; // Language code for API payload
  flag: string; // Flag emoji
  region: string; // Region for grouping
  status: "Available" | "Coming Soon";
  nativeSpeakers: number; // Native speakers in millions
  flagCode: any;
}
export const languageOptions: LanguageOption[] = mergedLanguages.map(
  (lang: any) => ({
    name: lang.name,
    code: lang.code,
    flag: lang.flag || "🌐",
    region: lang.region || "Unknown",
    status: lang.status || "Available",
    nativeSpeakers: lang.nativeSpeakers || 0,
    flagCode: lang.flagCode,
  }),
);

// Language data extracted from the CSV
export const languageOptionss: any[] = [
  // Indic Languages
  {
    name: "Assamese",
    code: "as",
    flag: "🇮🇳",
    region: "Indic",
    status: "Coming Soon",
    nativeSpeakers: 15,
  },
  {
    name: "Awadhi",
    code: "awa",
    flag: "🇮🇳",
    region: "Indic",
    status: "Available",
    nativeSpeakers: 38,
  },
  {
    name: "Bengali (India)",
    code: "bn-IN",
    flag: "🇮🇳",
    region: "Indic",
    status: "Available",
    nativeSpeakers: 98,
  },
  {
    name: "Bhojpuri",
    code: "bho",
    flag: "🇮🇳",
    region: "Indic",
    status: "Available",
    nativeSpeakers: 52,
  },
  {
    name: "Bodo",
    code: "brx",
    flag: "🇮🇳",
    region: "Indic",
    status: "Available",
    nativeSpeakers: 1.4,
  },
  {
    name: "Chhattisgarhi",
    code: "hne",
    flag: "🇮🇳",
    region: "Indic",
    status: "Available",
    nativeSpeakers: 18,
  },
  {
    name: "Dogri",
    code: "doi",
    flag: "🇮🇳",
    region: "Indic",
    status: "Available",
    nativeSpeakers: 2.3,
  },
  {
    name: "Garo",
    code: "grt",
    flag: "🇮🇳",
    region: "Indic",
    status: "Available",
    nativeSpeakers: 1.2,
  },
  {
    name: "Gondi",
    code: "gon",
    flag: "🇮🇳",
    region: "Indic",
    status: "Available",
    nativeSpeakers: 3,
  },
  {
    name: "Gujarati",
    code: "gu",
    flag: "🇮🇳",
    region: "Indic",
    status: "Coming Soon",
    nativeSpeakers: 56,
  },
  {
    name: "Haryanvi",
    code: "bgc",
    flag: "🇮🇳",
    region: "Indic",
    status: "Available",
    nativeSpeakers: 10,
  },
  {
    name: "Hindi",
    code: "hi",
    flag: "🇮🇳",
    region: "Indic",
    status: "Available",
    nativeSpeakers: 600,
  },
  {
    name: "Ho",
    code: "hoc",
    flag: "🇮🇳",
    region: "Indic",
    status: "Available",
    nativeSpeakers: 1.1,
  },
  {
    name: "Kannada",
    code: "kn",
    flag: "🇮🇳",
    region: "Indic",
    status: "Available",
    nativeSpeakers: 44,
  },
  {
    name: "Kashmiri",
    code: "ks",
    flag: "🇮🇳",
    region: "Indic",
    status: "Available",
    nativeSpeakers: 7,
  },
  {
    name: "Khasi",
    code: "kha",
    flag: "🇮🇳",
    region: "Indic",
    status: "Available",
    nativeSpeakers: 1.4,
  },
  {
    name: "Khond",
    code: "kxv",
    flag: "🇮🇳",
    region: "Indic",
    status: "Available",
    nativeSpeakers: 1.8,
  },
  {
    name: "Konkani",
    code: "kok",
    flag: "🇮🇳",
    region: "Indic",
    status: "Available",
    nativeSpeakers: 2.3,
  },
  {
    name: "Magahi",
    code: "mag",
    flag: "🇮🇳",
    region: "Indic",
    status: "Available",
    nativeSpeakers: 21,
  },
  {
    name: "Maithili",
    code: "mai",
    flag: "🇮🇳",
    region: "Indic",
    status: "Available",
    nativeSpeakers: 34,
  },
  {
    name: "Malayalam",
    code: "ml",
    flag: "🇮🇳",
    region: "Indic",
    status: "Coming Soon",
    nativeSpeakers: 35,
  },
  {
    name: "Manipuri",
    code: "mni",
    flag: "🇮🇳",
    region: "Indic",
    status: "Coming Soon",
    nativeSpeakers: 1.8,
  },
  {
    name: "Marathi",
    code: "mr",
    flag: "🇮🇳",
    region: "Indic",
    status: "Available",
    nativeSpeakers: 83,
  },
  {
    name: "Marwari",
    code: "mwr",
    flag: "🇮🇳",
    region: "Indic",
    status: "Available",
    nativeSpeakers: 22,
  },
  {
    name: "Mizo",
    code: "lus",
    flag: "🇮🇳",
    region: "Indic",
    status: "Available",
    nativeSpeakers: 1.1,
  },
  {
    name: "Mundari",
    code: "unr",
    flag: "🇮🇳",
    region: "Indic",
    status: "Available",
    nativeSpeakers: 1.2,
  },
  {
    name: "Nepali",
    code: "ne",
    flag: "🇳🇵",
    region: "Indic",
    status: "Available",
    nativeSpeakers: 16,
  },
  {
    name: "Odia",
    code: "or",
    flag: "🇮🇳",
    region: "Indic",
    status: "Coming Soon",
    nativeSpeakers: 38,
  },
  {
    name: "Punjabi",
    code: "pa",
    flag: "🇮🇳",
    region: "Indic",
    status: "Coming Soon",
    nativeSpeakers: 113,
  },
  {
    name: "Rajasthani",
    code: "raj",
    flag: "🇮🇳",
    region: "Indic",
    status: "Available",
    nativeSpeakers: 26,
  },
  {
    name: "Santali",
    code: "sat",
    flag: "🇮🇳",
    region: "Indic",
    status: "Available",
    nativeSpeakers: 7.6,
  },
  {
    name: "Sindhi",
    code: "sd",
    flag: "🇮🇳",
    region: "Indic",
    status: "Available",
    nativeSpeakers: 25,
  },
  {
    name: "Tamil",
    code: "ta",
    flag: "🇮🇳",
    region: "Indic",
    status: "Available",
    nativeSpeakers: 75,
  },
  {
    name: "Telugu",
    code: "te",
    flag: "🇮🇳",
    region: "Indic",
    status: "Coming Soon",
    nativeSpeakers: 82,
  },
  {
    name: "Tulu",
    code: "tcy",
    flag: "🇮🇳",
    region: "Indic",
    status: "Available",
    nativeSpeakers: 2,
  },
  {
    name: "Urdu",
    code: "ur",
    flag: "🇮🇳",
    region: "Indic",
    status: "Available",
    nativeSpeakers: 70,
  },
  {
    name: "Bagheli",
    code: "bfy",
    flag: "🇮🇳",
    region: "Indic",
    status: "Available",
    nativeSpeakers: 8,
  },
  {
    name: "Malvi",
    code: "mup",
    flag: "🇮🇳",
    region: "Indic",
    status: "Available",
    nativeSpeakers: 5.2,
  },

  // European Languages
  {
    name: "English (Global)",
    code: "en",
    flag: "🇺🇸",
    region: "European",
    status: "Available",
    nativeSpeakers: 1530,
  },
  {
    name: "French",
    code: "fr",
    flag: "🇫🇷",
    region: "European",
    status: "Available",
    nativeSpeakers: 312,
  },
  {
    name: "German",
    code: "de",
    flag: "🇩🇪",
    region: "European",
    status: "Available",
    nativeSpeakers: 95,
  },
  {
    name: "Italian",
    code: "it",
    flag: "🇮🇹",
    region: "European",
    status: "Available",
    nativeSpeakers: 65,
  },
  {
    name: "Spanish (Global)",
    code: "es",
    flag: "🇪🇸",
    region: "European",
    status: "Available",
    nativeSpeakers: 558,
  },
  {
    name: "Portuguese (Global)",
    code: "pt",
    flag: "🇵🇹",
    region: "European",
    status: "Available",
    nativeSpeakers: 267,
  },
  {
    name: "Russian",
    code: "ru",
    flag: "🇷🇺",
    region: "European",
    status: "Available",
    nativeSpeakers: 150,
  },
  {
    name: "Polish",
    code: "pl",
    flag: "🇵🇱",
    region: "European",
    status: "Available",
    nativeSpeakers: 40,
  },
  {
    name: "Dutch",
    code: "nl",
    flag: "🇳🇱",
    region: "European",
    status: "Available",
    nativeSpeakers: 24,
  },
  {
    name: "Swedish",
    code: "sv",
    flag: "🇸🇪",
    region: "European",
    status: "Available",
    nativeSpeakers: 10,
  },
  {
    name: "Norwegian",
    code: "no",
    flag: "🇳🇴",
    region: "European",
    status: "Available",
    nativeSpeakers: 4.5,
  },
  {
    name: "Danish",
    code: "da",
    flag: "🇩🇰",
    region: "European",
    status: "Available",
    nativeSpeakers: 6,
  },
  {
    name: "Finnish",
    code: "fi",
    flag: "🇫🇮",
    region: "European",
    status: "Available",
    nativeSpeakers: 5.4,
  },
  {
    name: "Hungarian",
    code: "hu",
    flag: "🇭🇺",
    region: "European",
    status: "Available",
    nativeSpeakers: 13,
  },
  {
    name: "Czech",
    code: "cs",
    flag: "🇨🇿",
    region: "European",
    status: "Available",
    nativeSpeakers: 10.7,
  },
  {
    name: "Slovak",
    code: "sk",
    flag: "🇸🇰",
    region: "European",
    status: "Available",
    nativeSpeakers: 5.2,
  },
  {
    name: "Slovenian",
    code: "sl",
    flag: "🇸🇮",
    region: "European",
    status: "Available",
    nativeSpeakers: 2.5,
  },
  {
    name: "Croatian",
    code: "hr",
    flag: "🇭🇷",
    region: "European",
    status: "Available",
    nativeSpeakers: 5,
  },
  {
    name: "Serbian",
    code: "sr",
    flag: "🇷🇸",
    region: "European",
    status: "Available",
    nativeSpeakers: 9,
  },
  {
    name: "Bulgarian",
    code: "bg",
    flag: "🇧🇬",
    region: "European",
    status: "Available",
    nativeSpeakers: 8,
  },
  {
    name: "Romanian",
    code: "ro",
    flag: "🇷🇴",
    region: "European",
    status: "Available",
    nativeSpeakers: 24,
  },
  {
    name: "Greek",
    code: "el",
    flag: "🇬🇷",
    region: "European",
    status: "Available",
    nativeSpeakers: 13.5,
  },
  {
    name: "Lithuanian",
    code: "lt",
    flag: "🇱🇹",
    region: "European",
    status: "Available",
    nativeSpeakers: 3,
  },
  {
    name: "Latvian",
    code: "lv",
    flag: "🇱🇻",
    region: "European",
    status: "Available",
    nativeSpeakers: 1.9,
  },
  {
    name: "Estonian",
    code: "et",
    flag: "🇪🇪",
    region: "European",
    status: "Available",
    nativeSpeakers: 1.1,
  },
  {
    name: "Albanian",
    code: "sq",
    flag: "🇦🇱",
    region: "European",
    status: "Available",
    nativeSpeakers: 7.6,
  },
  {
    name: "Macedonian",
    code: "mk",
    flag: "🇲🇰",
    region: "European",
    status: "Available",
    nativeSpeakers: 2.1,
  },
  {
    name: "Belarusian",
    code: "be",
    flag: "🇧🇾",
    region: "European",
    status: "Available",
    nativeSpeakers: 5.1,
  },
  {
    name: "Ukrainian",
    code: "uk",
    flag: "🇺🇦",
    region: "European",
    status: "Available",
    nativeSpeakers: 40,
  },
  {
    name: "Moldovan",
    code: "mo",
    flag: "🇲🇩",
    region: "European",
    status: "Available",
    nativeSpeakers: 2.6,
  },
  {
    name: "Catalan",
    code: "ca",
    flag: "🇪🇸",
    region: "European",
    status: "Available",
    nativeSpeakers: 10,
  },
  {
    name: "Basque",
    code: "eu",
    flag: "🇪🇸",
    region: "European",
    status: "Available",
    nativeSpeakers: 1.2,
  },
  {
    name: "Galician",
    code: "gl",
    flag: "🇪🇸",
    region: "European",
    status: "Available",
    nativeSpeakers: 2.4,
  },
  {
    name: "Welsh",
    code: "cy",
    flag: "🇬🇧",
    region: "European",
    status: "Available",
    nativeSpeakers: 0.9,
  },
  {
    name: "Irish",
    code: "ga",
    flag: "🇮🇪",
    region: "European",
    status: "Available",
    nativeSpeakers: 1.7,
  },
  {
    name: "Occitan",
    code: "oc",
    flag: "🇫🇷",
    region: "European",
    status: "Available",
    nativeSpeakers: 0.8,
  },
  {
    name: "Sardinian",
    code: "sc",
    flag: "🇮🇹",
    region: "European",
    status: "Available",
    nativeSpeakers: 1.35,
  },
  {
    name: "Low German",
    code: "nds",
    flag: "🇩🇪",
    region: "European",
    status: "Available",
    nativeSpeakers: 5,
  },
  {
    name: "Bavarian",
    code: "bar",
    flag: "🇩🇪",
    region: "European",
    status: "Available",
    nativeSpeakers: 14,
  },
  {
    name: "Sicilian",
    code: "scn",
    flag: "🇮🇹",
    region: "European",
    status: "Available",
    nativeSpeakers: 5,
  },
  {
    name: "Neapolitan",
    code: "nap",
    flag: "🇮🇹",
    region: "European",
    status: "Available",
    nativeSpeakers: 5.7,
  },

  // Asian Languages
  {
    name: "Chinese (Global)",
    code: "zh",
    flag: "🇨🇳",
    region: "Asian",
    status: "Available",
    nativeSpeakers: 1184,
  },
  {
    name: "Japanese",
    code: "ja",
    flag: "🇯🇵",
    region: "Asian",
    status: "Available",
    nativeSpeakers: 125,
  },
  {
    name: "Korean",
    code: "ko",
    flag: "🇰🇷",
    region: "Asian",
    status: "Available",
    nativeSpeakers: 82,
  },
  {
    name: "Vietnamese",
    code: "vi",
    flag: "🇻🇳",
    region: "Asian",
    status: "Available",
    nativeSpeakers: 85,
  },
  {
    name: "Thai",
    code: "th",
    flag: "🇹🇭",
    region: "Asian",
    status: "Available",
    nativeSpeakers: 71,
  },
  {
    name: "Indonesian",
    code: "id",
    flag: "🇮🇩",
    region: "Asian",
    status: "Available",
    nativeSpeakers: 199,
  },
  {
    name: "Malay",
    code: "ms",
    flag: "🇲🇾",
    region: "Asian",
    status: "Available",
    nativeSpeakers: 19,
  },
  {
    name: "Tagalog",
    code: "tl",
    flag: "🇵🇭",
    region: "Asian",
    status: "Available",
    nativeSpeakers: 28,
  },
  {
    name: "Cebuano",
    code: "ceb",
    flag: "🇵🇭",
    region: "Asian",
    status: "Available",
    nativeSpeakers: 22,
  },
  {
    name: "Hiligaynon",
    code: "hil",
    flag: "🇵🇭",
    region: "Asian",
    status: "Available",
    nativeSpeakers: 9,
  },
  {
    name: "Waray",
    code: "war",
    flag: "🇵🇭",
    region: "Asian",
    status: "Available",
    nativeSpeakers: 3.1,
  },
  {
    name: "Bikol",
    code: "bcl",
    flag: "🇵🇭",
    region: "Asian",
    status: "Available",
    nativeSpeakers: 2.5,
  },
  {
    name: "Pangasinan",
    code: "pag",
    flag: "🇵🇭",
    region: "Asian",
    status: "Available",
    nativeSpeakers: 1.2,
  },
  {
    name: "Kapampangan",
    code: "pam",
    flag: "🇵🇭",
    region: "Asian",
    status: "Available",
    nativeSpeakers: 2.9,
  },
  {
    name: "Ilocano",
    code: "ilo",
    flag: "🇵🇭",
    region: "Asian",
    status: "Available",
    nativeSpeakers: 9.1,
  },
  {
    name: "Javanese",
    code: "jv",
    flag: "🇮🇩",
    region: "Asian",
    status: "Available",
    nativeSpeakers: 69,
  },
  {
    name: "Lao",
    code: "lo",
    flag: "🇱🇦",
    region: "Asian",
    status: "Coming Soon",
    nativeSpeakers: 7,
  },
  {
    name: "Khmer",
    code: "km",
    flag: "🇰🇭",
    region: "Asian",
    status: "Coming Soon",
    nativeSpeakers: 16,
  },
  {
    name: "Burmese",
    code: "my",
    flag: "🇲🇲",
    region: "Asian",
    status: "Coming Soon",
    nativeSpeakers: 37,
  },
  {
    name: "Mon",
    code: "mnw",
    flag: "🇲🇲",
    region: "Asian",
    status: "Coming Soon",
    nativeSpeakers: 1.1,
  },
  {
    name: "Shan",
    code: "shn",
    flag: "🇲🇲",
    region: "Asian",
    status: "Coming Soon",
    nativeSpeakers: 5.2,
  },
  {
    name: "Tibetan",
    code: "bo",
    flag: "🇨🇳",
    region: "Asian",
    status: "Coming Soon",
    nativeSpeakers: 1.2,
  },
  {
    name: "Mongolian",
    code: "mn",
    flag: "🇲🇳",
    region: "Asian",
    status: "Available",
    nativeSpeakers: 5.7,
  },
  {
    name: "Hmong",
    code: "hmn",
    flag: "🇨🇳",
    region: "Asian",
    status: "Available",
    nativeSpeakers: 4.2,
  },
  {
    name: "Mien",
    code: "ium",
    flag: "🇨🇳",
    region: "Asian",
    status: "Available",
    nativeSpeakers: 2.7,
  },
  {
    name: "Tok Pisin",
    code: "tpi",
    flag: "🇵🇬",
    region: "Asian",
    status: "Available",
    nativeSpeakers: 5.4,
  },
  {
    name: "Sinhala",
    code: "si",
    flag: "🇱🇰",
    region: "Asian",
    status: "Coming Soon",
    nativeSpeakers: 17,
  },
  {
    name: "Dzongkha",
    code: "dz",
    flag: "🇧🇹",
    region: "Asian",
    status: "Coming Soon",
    nativeSpeakers: 1.7,
  },
  {
    name: "Fijian",
    code: "fj",
    flag: "🇫🇯",
    region: "Asian",
    status: "Available",
    nativeSpeakers: 1.4,
  },
  {
    name: "Tetum",
    code: "tet",
    flag: "🇹🇱",
    region: "Asian",
    status: "Available",
    nativeSpeakers: 1.2,
  },
  {
    name: "Sundanese",
    code: "su",
    flag: "🇮🇩",
    region: "Asian",
    status: "Available",
    nativeSpeakers: 42,
  },
  {
    name: "Madurese",
    code: "mad",
    flag: "🇮🇩",
    region: "Asian",
    status: "Available",
    nativeSpeakers: 13,
  },
  {
    name: "Buginese",
    code: "bug",
    flag: "🇮🇩",
    region: "Asian",
    status: "Available",
    nativeSpeakers: 5,
  },
  {
    name: "Acehnese",
    code: "ace",
    flag: "🇮🇩",
    region: "Asian",
    status: "Available",
    nativeSpeakers: 3.5,
  },

  // African Languages
  {
    name: "Swahili",
    code: "sw",
    flag: "🇹🇿",
    region: "African",
    status: "Available",
    nativeSpeakers: 16,
  },
  {
    name: "Amharic",
    code: "am",
    flag: "🇪🇹",
    region: "African",
    status: "Coming Soon",
    nativeSpeakers: 57,
  },
  {
    name: "Oromo",
    code: "om",
    flag: "🇪🇹",
    region: "African",
    status: "Available",
    nativeSpeakers: 37,
  },
  {
    name: "Tigrinya",
    code: "ti",
    flag: "🇪🇹",
    region: "African",
    status: "Coming Soon",
    nativeSpeakers: 7,
  },
  {
    name: "Somali",
    code: "so",
    flag: "🇸🇴",
    region: "African",
    status: "Available",
    nativeSpeakers: 21.8,
  },
  {
    name: "Hausa",
    code: "ha",
    flag: "🇳🇬",
    region: "African",
    status: "Available",
    nativeSpeakers: 70,
  },
  {
    name: "Yoruba",
    code: "yo",
    flag: "🇳🇬",
    region: "African",
    status: "Available",
    nativeSpeakers: 45,
  },
  {
    name: "Igbo",
    code: "ig",
    flag: "🇳🇬",
    region: "African",
    status: "Available",
    nativeSpeakers: 27,
  },
  {
    name: "Fulani",
    code: "ff",
    flag: "🇳🇬",
    region: "African",
    status: "Available",
    nativeSpeakers: 40,
  },
  {
    name: "Akan",
    code: "ak",
    flag: "🇬🇭",
    region: "African",
    status: "Available",
    nativeSpeakers: 11,
  },
  {
    name: "Twi",
    code: "tw",
    flag: "🇬🇭",
    region: "African",
    status: "Available",
    nativeSpeakers: 17,
  },
  {
    name: "Ewe",
    code: "ee",
    flag: "🇬🇭",
    region: "African",
    status: "Available",
    nativeSpeakers: 6.8,
  },
  {
    name: "Ga",
    code: "gaa",
    flag: "🇬🇭",
    region: "African",
    status: "Available",
    nativeSpeakers: 3.2,
  },
  {
    name: "Wolof",
    code: "wo",
    flag: "🇸🇳",
    region: "African",
    status: "Available",
    nativeSpeakers: 12,
  },
  {
    name: "Mandinka",
    code: "mnk",
    flag: "🇬🇲",
    region: "African",
    status: "Available",
    nativeSpeakers: 2.4,
  },
  {
    name: "Bambara",
    code: "bm",
    flag: "🇲🇱",
    region: "African",
    status: "Available",
    nativeSpeakers: 14,
  },
  {
    name: "Lingala",
    code: "ln",
    flag: "🇨🇩",
    region: "African",
    status: "Available",
    nativeSpeakers: 15,
  },
  {
    name: "Kikongo",
    code: "kg",
    flag: "🇨🇩",
    region: "African",
    status: "Available",
    nativeSpeakers: 10,
  },
  {
    name: "Kinyarwanda",
    code: "rw",
    flag: "🇷🇼",
    region: "African",
    status: "Available",
    nativeSpeakers: 12,
  },
  {
    name: "Kirundi",
    code: "rn",
    flag: "🇧🇮",
    region: "African",
    status: "Available",
    nativeSpeakers: 13,
  },
  {
    name: "Luganda",
    code: "lg",
    flag: "🇺🇬",
    region: "African",
    status: "Available",
    nativeSpeakers: 5.6,
  },
  {
    name: "Luo",
    code: "luo",
    flag: "🇰🇪",
    region: "African",
    status: "Available",
    nativeSpeakers: 5.3,
  },
  {
    name: "Kikuyu",
    code: "ki",
    flag: "🇰🇪",
    region: "African",
    status: "Available",
    nativeSpeakers: 8.1,
  },
  {
    name: "Shona",
    code: "sn",
    flag: "🇿🇼",
    region: "African",
    status: "Available",
    nativeSpeakers: 14.2,
  },
  {
    name: "Ndebele",
    code: "nd",
    flag: "🇿🇼",
    region: "African",
    status: "Available",
    nativeSpeakers: 2.1,
  },
  {
    name: "Zulu",
    code: "zu",
    flag: "🇿🇦",
    region: "African",
    status: "Available",
    nativeSpeakers: 12,
  },
  {
    name: "Xhosa",
    code: "xh",
    flag: "🇿🇦",
    region: "African",
    status: "Available",
    nativeSpeakers: 8.2,
  },
  {
    name: "Afrikaans",
    code: "af",
    flag: "🇿🇦",
    region: "African",
    status: "Available",
    nativeSpeakers: 7,
  },
  {
    name: "Sesotho",
    code: "st",
    flag: "🇱🇸",
    region: "African",
    status: "Available",
    nativeSpeakers: 5.6,
  },
  {
    name: "Tswana",
    code: "tn",
    flag: "🇧🇼",
    region: "African",
    status: "Available",
    nativeSpeakers: 4.1,
  },
  {
    name: "Swati",
    code: "ss",
    flag: "🇸🇿",
    region: "African",
    status: "Available",
    nativeSpeakers: 2.3,
  },
  {
    name: "Venda",
    code: "ve",
    flag: "🇿🇦",
    region: "African",
    status: "Available",
    nativeSpeakers: 1.2,
  },
  {
    name: "Tsonga",
    code: "ts",
    flag: "🇿🇦",
    region: "African",
    status: "Available",
    nativeSpeakers: 4.4,
  },
  {
    name: "Berber (Tamazight)",
    code: "ber",
    flag: "🇲🇦",
    region: "African",
    status: "Available",
    nativeSpeakers: 30,
  },
  {
    name: "Malagasy",
    code: "mg",
    flag: "🇲🇬",
    region: "African",
    status: "Available",
    nativeSpeakers: 18,
  },
  {
    name: "Chichewa",
    code: "ny",
    flag: "🇲🇼",
    region: "African",
    status: "Available",
    nativeSpeakers: 12,
  },
  {
    name: "Mossi",
    code: "mos",
    flag: "🇧🇫",
    region: "African",
    status: "Available",
    nativeSpeakers: 7.6,
  },
  {
    name: "Bemba",
    code: "bem",
    flag: "🇿🇲",
    region: "African",
    status: "Available",
    nativeSpeakers: 4.1,
  },
  {
    name: "Kamba",
    code: "kam",
    flag: "🇰🇪",
    region: "African",
    status: "Available",
    nativeSpeakers: 4.3,
  },
  {
    name: "Kongo",
    code: "kon",
    flag: "🇨🇩",
    region: "African",
    status: "Available",
    nativeSpeakers: 5.6,
  },
  {
    name: "Sango",
    code: "sg",
    flag: "🇨🇫",
    region: "African",
    status: "Available",
    nativeSpeakers: 2,
  },
  {
    name: "Wolaytta",
    code: "wal",
    flag: "🇪🇹",
    region: "African",
    status: "Available",
    nativeSpeakers: 2,
  },
  {
    name: "Sidamo",
    code: "sid",
    flag: "🇪🇹",
    region: "African",
    status: "Available",
    nativeSpeakers: 3,
  },

  // Middle Eastern Languages
  {
    name: "Arabic (Global)",
    code: "ar",
    flag: "🇸🇦",
    region: "Middle Eastern",
    status: "Available",
    nativeSpeakers: 422,
  },
  {
    name: "Hebrew",
    code: "he",
    flag: "🇮🇱",
    region: "Middle Eastern",
    status: "Available",
    nativeSpeakers: 9,
  },
  {
    name: "Persian",
    code: "fa",
    flag: "🇮🇷",
    region: "Middle Eastern",
    status: "Available",
    nativeSpeakers: 62,
  },
  {
    name: "Kurdish (Sorani)",
    code: "ckb",
    flag: "🇮🇶",
    region: "Middle Eastern",
    status: "Available",
    nativeSpeakers: 8,
  },
  {
    name: "Kurdish (Kurmanji)",
    code: "kmr",
    flag: "🇹🇷",
    region: "Middle Eastern",
    status: "Available",
    nativeSpeakers: 15,
  },
  {
    name: "Pashto",
    code: "ps",
    flag: "🇦🇫",
    region: "Middle Eastern",
    status: "Available",
    nativeSpeakers: 60,
  },
  {
    name: "Dari",
    code: "prs",
    flag: "🇦🇫",
    region: "Middle Eastern",
    status: "Available",
    nativeSpeakers: 25,
  },
  {
    name: "Tajik",
    code: "tg",
    flag: "🇹🇯",
    region: "Middle Eastern",
    status: "Available",
    nativeSpeakers: 8.4,
  },
  {
    name: "Uyghur",
    code: "ug",
    flag: "🇨🇳",
    region: "Middle Eastern",
    status: "Available",
    nativeSpeakers: 12,
  },
  {
    name: "Kazakh",
    code: "kk",
    flag: "🇰🇿",
    region: "Middle Eastern",
    status: "Available",
    nativeSpeakers: 13,
  },
  {
    name: "Kyrgyz",
    code: "ky",
    flag: "🇰🇬",
    region: "Middle Eastern",
    status: "Available",
    nativeSpeakers: 4.4,
  },
  {
    name: "Uzbek",
    code: "uz",
    flag: "🇺🇿",
    region: "Middle Eastern",
    status: "Available",
    nativeSpeakers: 34,
  },
  {
    name: "Turkish",
    code: "tr",
    flag: "🇹🇷",
    region: "Middle Eastern",
    status: "Available",
    nativeSpeakers: 88,
  },
  {
    name: "Turkmen",
    code: "tk",
    flag: "🇹🇲",
    region: "Middle Eastern",
    status: "Available",
    nativeSpeakers: 3.4,
  },
  {
    name: "Azerbaijani",
    code: "az",
    flag: "🇦🇿",
    region: "Middle Eastern",
    status: "Available",
    nativeSpeakers: 23,
  },
  {
    name: "Armenian",
    code: "hy",
    flag: "🇦🇲",
    region: "Middle Eastern",
    status: "Available",
    nativeSpeakers: 6.7,
  },
  {
    name: "Georgian",
    code: "ka",
    flag: "🇬🇪",
    region: "Middle Eastern",
    status: "Coming Soon",
    nativeSpeakers: 3.7,
  },
  {
    name: "Chechen",
    code: "ce",
    flag: "🇷🇺",
    region: "Middle Eastern",
    status: "Available",
    nativeSpeakers: 1.8,
  },

  // South American Languages
  {
    name: "Quechua",
    code: "qu",
    flag: "🇵🇪",
    region: "South American",
    status: "Available",
    nativeSpeakers: 8.9,
  },
  {
    name: "Aymara",
    code: "ay",
    flag: "🇧🇴",
    region: "South American",
    status: "Available",
    nativeSpeakers: 2.8,
  },
  {
    name: "Guarani",
    code: "gn",
    flag: "🇵🇾",
    region: "South American",
    status: "Available",
    nativeSpeakers: 6.5,
  },
  {
    name: "Haitian Creole",
    code: "ht",
    flag: "🇭🇹",
    region: "South American",
    status: "Available",
    nativeSpeakers: 12,
  },
  {
    name: "Jamaican Patois",
    code: "jam",
    flag: "🇯🇲",
    region: "South American",
    status: "Available",
    nativeSpeakers: 3.2,
  },
  {
    name: "Nahuatl",
    code: "nah",
    flag: "🇲🇽",
    region: "South American",
    status: "Available",
    nativeSpeakers: 1.7,
  },
  {
    name: "Maya (K'iche')",
    code: "quc",
    flag: "🇬🇹",
    region: "South American",
    status: "Available",
    nativeSpeakers: 2.3,
  },
  {
    name: "Maya (Q'eqchi')",
    code: "kek",
    flag: "🇬🇹",
    region: "South American",
    status: "Available",
    nativeSpeakers: 1.3,
  },
];

// Helper functions
// export const getAvailableLanguages = (): LanguageOption[] => {
//   console.log("language options",languageOptions);

//   return languageOptions.filter(lang => lang.status === 'Available');
// };
export const getAvailableLanguages = (): LanguageOption[] => {
  return languageOptions.filter(
    (lang) =>
      typeof lang.status === "string" &&
      lang.status.toLowerCase() === "available",
  );
};

export const getLanguagesByRegion = (region: string): LanguageOption[] => {
  return languageOptions.filter(
    (lang) => lang.region === region && lang.status === "Available",
  );
};

export const direct_languages = [
  "Assamese",
  "Awadhi",
  "Bagri",
  "Bengali",
  "Bhili",
  "Bhojpuri",
  "Bodo",
  "Braj",
  "Bundeli",
  "Chhattisgarhi",
  "Dogri",
  "English",
  "Garhwali",
  "Garo",
  "Gujarati",
  "Harouti",
  "Haryanvi",
  "Hindi",
  "Kangri",
  "Kannada",
  "Kashmiri",
  "Konkani",
  "Kumaoni",
  "Kurukh",
  "Magahi",
  "Maithili",
  "Malayalam",
  "Manipuri",
  "Marathi",
  "Marwadi",
  "Nepali",
  "Nimadi",
  "Odia",
  "Pahari Mahasui",
  "Punjabi",
  "Rajasthani",
  "Sanskrit",
  "Santali",
  "Sindhi",
  "Surgujia",
  "Tamil",
  "Telugu",
  "Tulu",
  "Urdu",
  "Wagdi",
];

const directLanguageFlags: Record<string, string> = {
  Assamese: "🇮🇳",
  Awadhi: "🇮🇳",
  Bagri: "🇮🇳",
  Bengali: "🇮🇳",
  Bhili: "🇮🇳",
  Bhojpuri: "🇮🇳",
  Bodo: "🇮🇳",
  Braj: "🇮🇳",
  Bundeli: "🇮🇳",
  Chhattisgarhi: "🇮🇳",
  Dogri: "🇮🇳",
  English: "🇺🇸",
  Garhwali: "🇮🇳",
  Garo: "🇮🇳",
  Gujarati: "🇮🇳",
  Harouti: "🇮🇳",
  Haryanvi: "🇮🇳",
  Hindi: "🇮🇳",
  Kangri: "🇮🇳",
  Kannada: "🇮🇳",
  Kashmiri: "🇮🇳",
  Konkani: "🇮🇳",
  Kumaoni: "🇮🇳",
  Kurukh: "🇮🇳",
  Magahi: "🇮🇳",
  Maithili: "🇮🇳",
  Malayalam: "🇮🇳",
  Manipuri: "🇮🇳",
  Marathi: "🇮🇳",
  Marwadi: "🇮🇳",
  Nepali: "🇳🇵",
  Nimadi: "🇮🇳",
  Odia: "🇮🇳",
  "Pahari Mahasui": "🇮🇳",
  Punjabi: "🇮🇳",
  Rajasthani: "🇮🇳",
  Sanskrit: "🇮🇳",
  Santali: "🇮🇳",
  Sindhi: "🇮🇳",
  Surgujia: "🇮🇳",
  Tamil: "🇮🇳",
  Telugu: "🇮🇳",
  Tulu: "🇮🇳",
  Urdu: "🇮🇳",
  Wagdi: "🇮🇳",
};

export const getDirectLanguages = () => {
  return direct_languages.map((name) => {
    const langDetail = languageOptions.find(
      (l) => l.name === name || l.name.startsWith(name),
    );
    return {
      name,
      code: langDetail ? langDetail.code : name,
      flagCode: directLanguageFlags[name] || langDetail?.flagCode || "🌐",
      flag:
        langDetail?.flag ||
        (directLanguageFlags[name] === "🇮🇳"
          ? "/data/flags/4x3/in.svg"
          : "/data/flags/4x3/un.svg"),
      region: "Direct",
      status: "Available" as const,
      nativeSpeakers: 0,
    };
  });
};

export const getLanguageNameByCode = (code: string): string => {
  if (code === "hi-en" || code === "med-en") return code;
  if (direct_languages.includes(code)) return code;
  const lang = languageOptions.find((l) => l.code === code);
  return lang ? lang.name : code;
};

export const getLanguagesWithRegion = () => {
  return mergedRegions.map((region) => ({
    region: region.name,
    description: region.description,
    languages: region.languages.filter((lang) => lang.status === "available"),
  }));
};

export const getSTTMedLanguagesWithRegion = () => {
  return STTMedMergedRegions.map((region) => ({
    region: region.name,
    description: region.description,
    languages: region.languages.filter(
      (lang) => lang.status && lang.status.toLowerCase() === "available",
    ),
  }));
};

export const getLanguageByCode = (code: string): LanguageOption | undefined => {
  return languageOptions.find((lang) => lang.code === code);
};

export const getLanguageByName = (name: string): LanguageOption | undefined => {
  return languageOptions.find((lang) => lang.name === name);
};

// Get popular languages (top 20 by native speakers)
export const getPopularLanguages = (): LanguageOption[] => {
  return languageOptions
    .filter((lang) => lang.status === "Available")
    .sort((a, b) => b.nativeSpeakers - a.nativeSpeakers)
    .slice(0, 20);
};

// Get all regions
export const getRegions = (): string[] => {
  return [...new Set(languageOptions.map((lang) => lang.region))].sort();
};
