/**
 * 🌍 Flag Mapping for Language Codes
 * Maps language code → country flag (ISO 3166-1 alpha-2)
 * All flags use https://flagicons.lipis.dev
 */

export const languageToFlag: Record<
  string,
  { code: string; emoji: string }
> = {
  // 🇮🇳 Indic Languages (India)
  as: { code: "in", emoji: "🇮🇳" },
  awa: { code: "in", emoji: "🇮🇳" },
  bn: { code: "bd", emoji: "🇧🇩" },
  "bn-IN": { code: "in", emoji: "🇮🇳" },
  "bn-BD": { code: "bd", emoji: "🇧🇩" },
  bho: { code: "in", emoji: "🇮🇳" },
  brx: { code: "in", emoji: "🇮🇳" },
  hne: { code: "in", emoji: "🇮🇳" },
  doi: { code: "in", emoji: "🇮🇳" },
  grt: { code: "in", emoji: "🇮🇳" },
  gon: { code: "in", emoji: "🇮🇳" },
  gu: { code: "in", emoji: "🇮🇳" },
  bgc: { code: "in", emoji: "🇮🇳" },
  hi: { code: "in", emoji: "🇮🇳" },
  hoc: { code: "in", emoji: "🇮🇳" },
  kn: { code: "in", emoji: "🇮🇳" },
  ks: { code: "in", emoji: "🇮🇳" },
  kha: { code: "in", emoji: "🇮🇳" },
  kok: { code: "in", emoji: "🇮🇳" },
  mag: { code: "in", emoji: "🇮🇳" },
  mai: { code: "in", emoji: "🇮🇳" },
  ml: { code: "in", emoji: "🇮🇳" },
  mni: { code: "in", emoji: "🇮🇳" },
  mr: { code: "in", emoji: "🇮🇳" },
  mwr: { code: "in", emoji: "🇮🇳" },
  lus: { code: "in", emoji: "🇮🇳" },
  unr: { code: "in", emoji: "🇮🇳" },
  ne: { code: "np", emoji: "🇳🇵" },
  or: { code: "in", emoji: "🇮🇳" },
  pa: { code: "in", emoji: "🇮🇳" },
  raj: { code: "in", emoji: "🇮🇳" },
  sat: { code: "in", emoji: "🇮🇳" },
  sd: { code: "in", emoji: "🇮🇳" },
  ta: { code: "in", emoji: "🇮🇳" },
  te: { code: "in", emoji: "🇮🇳" },
  tcy: { code: "in", emoji: "🇮🇳" },
  ur: { code: "in", emoji: "🇮🇳" },
  bfy: { code: "in", emoji: "🇮🇳" },
  mup: { code: "in", emoji: "🇮🇳" },

  // 🇺🇸 English Variants
  en: { code: "us", emoji: "🇺🇸" },
  "en-GB": { code: "gb", emoji: "🇬🇧" },
  "en-US": { code: "us", emoji: "🇺🇸" },
  "en-IN": { code: "in", emoji: "🇮🇳" },
  "en-AU": { code: "au", emoji: "🇦🇺" },
  "en-CA": { code: "ca", emoji: "🇨🇦" },
  "en-ZA": { code: "za", emoji: "🇿🇦" },
  "en-NZ": { code: "nz", emoji: "🇳🇿" },
  "en-IE": { code: "ie", emoji: "🇮🇪" },

  // 🇫🇷 French Variants
  fr: { code: "fr", emoji: "🇫🇷" },
  "fr-FR": { code: "fr", emoji: "🇫🇷" },
  "fr-CA": { code: "ca", emoji: "🇨🇦" },
  "fr-BE": { code: "be", emoji: "🇧🇪" },
  "fr-CH": { code: "ch", emoji: "🇨🇭" },
  "fr-AF": { code: "cm", emoji: "🇨🇲" },

  // 🇪🇸 Spanish Variants
  es: { code: "es", emoji: "🇪🇸" },
  "es-ES": { code: "es", emoji: "🇪🇸" },
  "es-MX": { code: "mx", emoji: "🇲🇽" },
  "es-CO": { code: "co", emoji: "🇨🇴" },
  "es-AR": { code: "ar", emoji: "🇦🇷" },
  "es-CL": { code: "cl", emoji: "🇨🇱" },

  // 🇵🇹 Portuguese Variants
  pt: { code: "pt", emoji: "🇵🇹" },
  "pt-BR": { code: "br", emoji: "🇧🇷" },
  "pt-PT": { code: "pt", emoji: "🇵🇹" },
  "pt-AF": { code: "ao", emoji: "🇦🇴" },

  // 🇩🇪 Germanic / European
  de: { code: "de", emoji: "🇩🇪" },
  nl: { code: "nl", emoji: "🇳🇱" },
  sv: { code: "se", emoji: "🇸🇪" },
  no: { code: "no", emoji: "🇳🇴" },
  da: { code: "dk", emoji: "🇩🇰" },
  fi: { code: "fi", emoji: "🇫🇮" },
  hu: { code: "hu", emoji: "🇭🇺" },
  cs: { code: "cz", emoji: "🇨🇿" },
  sk: { code: "sk", emoji: "🇸🇰" },
  sl: { code: "si", emoji: "🇸🇮" },
  hr: { code: "hr", emoji: "🇭🇷" },
  sr: { code: "rs", emoji: "🇷🇸" },
  bg: { code: "bg", emoji: "🇧🇬" },
  ro: { code: "ro", emoji: "🇷🇴" },
  el: { code: "gr", emoji: "🇬🇷" },
  lt: { code: "lt", emoji: "🇱🇹" },
  lv: { code: "lv", emoji: "🇱🇻" },
  et: { code: "ee", emoji: "🇪🇪" },
  sq: { code: "al", emoji: "🇦🇱" },
  mk: { code: "mk", emoji: "🇲🇰" },
  be: { code: "by", emoji: "🇧🇾" },
  uk: { code: "ua", emoji: "🇺🇦" },
  it: { code: "it", emoji: "🇮🇹" },
  pl: { code: "pl", emoji: "🇵🇱" },
  ca: { code: "es", emoji: "🇪🇸" },
  eu: { code: "es", emoji: "🇪🇸" },
  gl: { code: "es", emoji: "🇪🇸" },
  cy: { code: "gb", emoji: "🇬🇧" },
  ga: { code: "ie", emoji: "🇮🇪" },
  oc: { code: "fr", emoji: "🇫🇷" },
  sc: { code: "it", emoji: "🇮🇹" },
  nds: { code: "de", emoji: "🇩🇪" },
  bar: { code: "de", emoji: "🇩🇪" },
  scn: { code: "it", emoji: "🇮🇹" },
  nap: { code: "it", emoji: "🇮🇹" },

  // 🇨🇳 Asian
  zh: { code: "cn", emoji: "🇨🇳" },
  "zh-CN": { code: "cn", emoji: "🇨🇳" },
  "zh-HK": { code: "hk", emoji: "🇭🇰" },
  wuu: { code: "cn", emoji: "🇨🇳" },
  nan: { code: "cn", emoji: "🇨🇳" },
  hak: { code: "cn", emoji: "🇨🇳" },
  ja: { code: "jp", emoji: "🇯🇵" },
  ko: { code: "kr", emoji: "🇰🇷" },
  vi: { code: "vn", emoji: "🇻🇳" },
  th: { code: "th", emoji: "🇹🇭" },
  id: { code: "id", emoji: "🇮🇩" },
  ms: { code: "my", emoji: "🇲🇾" },
  tl: { code: "ph", emoji: "🇵🇭" },
  ceb: { code: "ph", emoji: "🇵🇭" },
  hil: { code: "ph", emoji: "🇵🇭" },
  war: { code: "ph", emoji: "🇵🇭" },
  bcl: { code: "ph", emoji: "🇵🇭" },
  pag: { code: "ph", emoji: "🇵🇭" },
  pam: { code: "ph", emoji: "🇵🇭" },
  ilo: { code: "ph", emoji: "🇵🇭" },
  jv: { code: "id", emoji: "🇮🇩" },
  lo: { code: "la", emoji: "🇱🇦" },
  km: { code: "kh", emoji: "🇰🇭" },
  my: { code: "mm", emoji: "🇲🇲" },
  mnw: { code: "mm", emoji: "🇲🇲" },
  shn: { code: "mm", emoji: "🇲🇲" },
  bo: { code: "cn", emoji: "🇨🇳" },
  mn: { code: "mn", emoji: "🇲🇳" },
  hmn: { code: "cn", emoji: "🇨🇳" },
  ium: { code: "la", emoji: "🇱🇦" },
  tpi: { code: "pg", emoji: "🇵🇬" },
  si: { code: "lk", emoji: "🇱🇰" },
  dz: { code: "bt", emoji: "🇧🇹" },
  fj: { code: "fj", emoji: "🇫🇯" },
  tet: { code: "tl", emoji: "🇹🇱" },
  su: { code: "id", emoji: "🇮🇩" },
  mad: { code: "id", emoji: "🇮🇩" },
  gan: { code: "cn", emoji: "🇨🇳" },
  hsn: { code: "cn", emoji: "🇨🇳" },
  bug: { code: "id", emoji: "🇮🇩" },
  ace: { code: "id", emoji: "🇮🇩" },

  // 🇸🇦 Middle Eastern
  ar: { code: "sa", emoji: "🇸🇦" },
  "ar-EG": { code: "eg", emoji: "🇪🇬" },
  "ar-AE": { code: "ae", emoji: "🇦🇪" },
  "ar-LB": { code: "lb", emoji: "🇱🇧" },
  "ar-SD": { code: "sd", emoji: "🇸🇩" },
  "ar-IQ": { code: "iq", emoji: "🇮🇶" },
  "ar-MA": { code: "ma", emoji: "🇲🇦" },
  "ar-TD": { code: "td", emoji: "🇹🇩" },
  he: { code: "il", emoji: "🇮🇱" },
  fa: { code: "ir", emoji: "🇮🇷" },
  ckb: { code: "iq", emoji: "🇮🇶" },
  kmr: { code: "tr", emoji: "🇹🇷" },
  ps: { code: "af", emoji: "🇦🇫" },
  bal: { code: "pk", emoji: "🇵🇰" },
  prs: { code: "af", emoji: "🇦🇫" },
  tg: { code: "tj", emoji: "🇹🇯" },
  ug: { code: "cn", emoji: "🇨🇳" },
  kk: { code: "kz", emoji: "🇰🇿" },
  ky: { code: "kg", emoji: "🇰🇬" },
  uz: { code: "uz", emoji: "🇺🇿" },
  tr: { code: "tr", emoji: "🇹🇷" },
  tk: { code: "tm", emoji: "🇹🇲" },
  az: { code: "az", emoji: "🇦🇿" },
  hy: { code: "am", emoji: "🇦🇲" },
  ka: { code: "ge", emoji: "🇬🇪" },
  ce: { code: "ru", emoji: "🇷🇺" },

  // 🇿🇦 African
  sw: { code: "tz", emoji: "🇹🇿" },
  am: { code: "et", emoji: "🇪🇹" },
  om: { code: "et", emoji: "🇪🇹" },
  ti: { code: "er", emoji: "🇪🇷" },
  so: { code: "so", emoji: "🇸🇴" },
  ha: { code: "ng", emoji: "🇳🇬" },
  yo: { code: "ng", emoji: "🇳🇬" },
  ig: { code: "ng", emoji: "🇳🇬" },
  ff: { code: "sn", emoji: "🇸🇳" },
  ak: { code: "gh", emoji: "🇬🇭" },
  tw: { code: "gh", emoji: "🇬🇭" },
  ee: { code: "gh", emoji: "🇬🇭" },
  gaa: { code: "gh", emoji: "🇬🇭" },
  wo: { code: "sn", emoji: "🇸🇳" },
  mnk: { code: "gm", emoji: "🇬🇲" },
  bm: { code: "ml", emoji: "🇲🇱" },
  ln: { code: "cd", emoji: "🇨🇩" },
  kg: { code: "cd", emoji: "🇨🇩" },
  rw: { code: "rw", emoji: "🇷🇼" },
  rn: { code: "bi", emoji: "🇧🇮" },
  lg: { code: "ug", emoji: "🇺🇬" },
  luo: { code: "ke", emoji: "🇰🇪" },
  ki: { code: "ke", emoji: "🇰🇪" },
  ke: { code: "ke", emoji: "🇰🇪" },
  sn: { code: "zw", emoji: "🇿🇼" },
  nd: { code: "zw", emoji: "🇿🇼" },
  zu: { code: "za", emoji: "🇿🇦" },
  xh: { code: "za", emoji: "🇿🇦" },
  af: { code: "za", emoji: "🇿🇦" },
  st: { code: "ls", emoji: "🇱🇸" },
  tn: { code: "bw", emoji: "🇧🇼" },
  ss: { code: "sz", emoji: "🇸🇿" },
  ve: { code: "za", emoji: "🇿🇦" },
  ts: { code: "za", emoji: "🇿🇦" },
  ber: { code: "ma", emoji: "🇲🇦" },
  mg: { code: "mg", emoji: "🇲🇬" },
  ny: { code: "mw", emoji: "🇲🇼" },
  mos: { code: "bf", emoji: "🇧🇫" },
  bem: { code: "zm", emoji: "🇿🇲" },
  kam: { code: "ke", emoji: "🇰🇪" },
  kon: { code: "cg", emoji: "🇨🇬" },
  sg: { code: "cf", emoji: "🇨🇫" },
  cg: { code: "cg", emoji: "🇨🇬" },
  wal: { code: "et", emoji: "🇪🇹" },
  sid: { code: "et", emoji: "🇪🇹" },

  // 🇧🇷 South American
  qu: { code: "pe", emoji: "🇵🇪" },
  ay: { code: "bo", emoji: "🇧🇴" },
  gn: { code: "py", emoji: "🇵🇾" },
  ht: { code: "ht", emoji: "🇭🇹" },
  jam: { code: "jm", emoji: "🇯🇲" },
  nah: { code: "mx", emoji: "🇲🇽" },
  quc: { code: "gt", emoji: "🇬🇹" },
  kek: { code: "gt", emoji: "🇬🇹" },

  //RUSSIA
  ru: { code: "ru", emoji: "🇷🇺" },

  "med-ko": { code: "kr", emoji: "🇰🇷" },
  "med-ja": { code: "jp", emoji: "🇯🇵" }, 
 "med-en": { code: "us", emoji: "🇺🇸" },

};
